/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.efreet.gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JvmInfo jInfo = JvmInfo.current();
        System.out.println(new App().getGreeting());
        System.out.println(jInfo.getMajor());
    }
}
